name: Register AWS ECS Task Definition
description: Registers a Task Definition in AWS ECS

branding:
  icon: activity
  color: red

inputs:
  family:
    description: The family is used as a name for your task definition. Up to 255 letters (uppercase and lowercase), numbers, and hyphens are allowed.
    required: true
  template:
    description: The path to the AWS ECS Task Definition template to use
    required: false
  container-images:
    description: A JSON map of containers and their respective images to use
    required: false
  environment-vars:
    description: A JSON map of environment variables that will be replaced in the template (on all containers)
    required: false

outputs:
  task-definition-arn:
    description: The registered Task Definition ARN

runs:
  using: node12
  main: index.js